---
# Production environment override
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php-prod
    build:
      context: .
      target: frankenphp_prod
      
    volumes:
      - ./public/upload:/app/public/upload
      - ./public/turnament:/app/public/turnament
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      SERVER_NAME: ${SERVER_NAME}, php:80
