<?php

declare(strict_types=1);

namespace App\Repository;

/**
 * BoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardRepository extends \Doctrine\ORM\EntityRepository
{
}
