<?php

declare(strict_types=1);

namespace App\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByNames($firstName, $lastName)
    {
		$result = $this->createQueryBuilder('p')
            ->where('p.firstName = :firstName')
            ->andWhere('p.lastName = :lastName') 
            ->setParameter('firstName', $firstName)
            ->setParameter('lastName', $lastName)
            ->getQuery()
		    ->getResult();
        if (is_array($result))
            if (count($result) > 0)
                return $result[0];
            else
                return null;
        return $result;
    }

    public function getNewFakeFsb() {
		while (true) {
            $fsb = strval(random_int(-9999, -1));
            if ($this->findOneByFsb($fsb) == null)
                return $fsb;
        }
    }
}
