<?php

declare(strict_types=1);

namespace App\Repository;

/**
 * TurnamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnamentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMonth($year, $month)
    {
        $from = \DateTime::createFromFormat('Y/m/d H:i:s', "$year/$month/01 00:00:00");
        $to = \DateTime::createFromFormat('Y/m/d H:i:s', "$year/$month/01 23:59:59");
        $to->modify('last day of this month');

        return $this->findByInterval($from, $to);
    }

	private function findByInterval($from, $to)
	{
		return $this->createQueryBuilder('t')
            ->where('t.date >= :from')
            ->andWhere('t.date <= :to') 
            ->setParameter('from', $from)
            ->setParameter('to', $to)
            ->getQuery()
		    ->getResult();
	}
}
